theme: jekyll-theme-minimal
title: articles.inqk.net
description: Usually more extended thoughts by Michael Camilleri.
timezone: Asia/Tokyo
author: Michael Camilleri

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/list/:num/"