title: articles.inqk.net
description: Usually more extended thoughts by [Michael Camilleri](https://inqk.net/).
timezone: Asia/Tokyo
author: Michael Camilleri

paginate: 10
paginate_path: "/list/:num/"
