title: articles.inqk.net
description: Usually more extended thoughts by [Michael Camilleri](https://inqk.net/).
url: http://articles.inqk.net
timezone: Asia/Tokyo
author: Michael Camilleri

include: ['_pages']

future: true

paginate: 10
paginate_path: "/list/:num/"

markdown: CommonMark

commonmark:
  options: ["FOOTNOTES", "SMART", "UNSAFE"]
